//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.LibraryRss.WebUi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MB.LibraryRss.WebUi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF OBJECT_ID(&apos;Element&apos;) IS NOT NULL
        ///  BEGIN
        ///    DROP TABLE [Element]
        ///  END
        ///GO
        ///
        ///IF OBJECT_ID(&apos;Feed&apos;) IS NOT NULL
        ///  BEGIN
        ///    DROP TABLE [Feed]
        ///  END
        ///GO.
        /// </summary>
        internal static string DropSql {
            get {
                return ResourceManager.GetString("DropSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET NUMERIC_ROUNDABORT OFF
        ///GO
        ///SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
        ///GO
        ///IF EXISTS ( SELECT
        ///              *
        ///            FROM
        ///              tempdb..sysobjects
        ///            WHERE
        ///              id = OBJECT_ID(&apos;tempdb..#tmpErrors&apos;) )
        ///  DROP TABLE #tmpErrors
        ///GO
        ///CREATE TABLE #tmpErrors ( Error INT )
        ///GO
        ///SET XACT_ABORT ON
        ///GO
        ///SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
        ///GO
        ///BEGIN TRANSACTION
        ///GO
        ///PRINT N&apos;Creating [dbo].[Feeds]&apos;
        ///GO
        ///CREAT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitSql {
            get {
                return ResourceManager.GetString("InitSql", resourceCulture);
            }
        }
    }
}
